name: LUcompute
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.6
    - numpy=1.13
    - scipy=0.19
    - sympy=1.1
    - pandas=0.21
    - ipywidgets=7.0
    - matplotlib=2.0
    - notebook=5.2
    - widgetsnbextension=3.0
    - jupyter_contrib_nbextensions=0.3
    - jupyter_nbextensions_configurator=0.2
